### ISSUE TITLE
GitHub jobs failing due to permissions error

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/TEI#2399]
In GitHub, the test job fail when running the Tests from the Stylesheets repo due to a permissions error:

https://github.com/TEIC/TEI/actions/runs/4224874009/jobs/7336394765#step:6:72

From what I can tell, this is a fairly widespread issue for containers running in GitHub runners due to a recent debian security upgrade (see threads here: https://github.com/actions/runner-images/issues/6775 and https://github.com/actions/checkout/issues/1169) 

Following the advice from https://github.com/actions/checkout/issues/1169, I _think_ marking the directory as safe in Git after the [checkout step](https://github.com/TEIC/TEI/blob/b49da7f1651746181737b125a591621f7438cdc7/.github/workflows/test.yml#L22-L27) would work to solve the issue until `actions/checkout` implements a fix:

```yaml
      - name: Checkout Stylesheets repo
        uses: actions/checkout@v3
        with:
          repository: TEIC/Stylesheets
          ref: dev
          path: Stylesheets
      - name: Fix permissions
         run: git config --system --add safe.directory /github/workspace
```
